BROWSER: str = ""
CHROME_DRIVER_PATH: str = ""
FIREFOX_DRIVER_PATH: str = ""
UI_URL: str = "http://automationpractice.com"
API_URL: str = "https://api.github.com"
GITHUB_TOKEN: str = ""
GITHUB_USERNAME: str = ""
