BROWSER: str = "chrome"
CHROME_DRIVER_PATH: str = "C:\\Users\\max.godfrey\\Documents\\Selenium\\chromedriver.exe"
FIREFOX_DRIVER_PATH: str = ""
UI_URL: str = "http://automationpractice.com"
API_URL: str = "https://api.github.com"
GITHUB_TOKEN: str = "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"
GITHUB_USERNAME: str = "maxgodfrey92"
